// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as InjectedForLoopJs from "./InjectedForLoop.js";

function make(state, getNext) {
  var innerDict = {};
  innerDict[Symbol.asyncIterator] = (function () {
      return {
              next: (async function () {
                  var value = await getNext(state);
                  return {
                          value: value,
                          done: Belt_Option.isNone(value)
                        };
                })
            };
    });
  return innerDict;
}

function forAwaitOf(prim0, prim1) {
  InjectedForLoopJs.forAwaitOf(prim0, prim1);
}

var $$break = InjectedForLoopJs.kBreak;

var $$continue = InjectedForLoopJs.kContinue;

export {
  make ,
  forAwaitOf ,
  $$break ,
  $$continue ,
}
/* break Not a pure module */
