// Generated by ReScript, PLEASE EDIT WITH CARE


function make(state, next, isDone) {
  var innerDict = {};
  innerDict[Symbol.iterator] = (function () {
      return {
              next: (function () {
                  var done = isDone(state);
                  return {
                          value: next(state),
                          done: done
                        };
                })
            };
    });
  return innerDict;
}

var Iterator = {
  make: make
};

var counter = make({
      contents: 0
    }, (function (count) {
        var value = count.contents;
        count.contents = count.contents + 1 | 0;
        return value;
      }), (function (count) {
        return count.contents > 10;
      }));

// console.log(counter[Symbol.iterator])


for (let count of counter) {
  console.log(count)
}
;

export {
  Iterator ,
  counter ,
}
/* counter Not a pure module */
