// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function makeWithNextInput(state, next) {
  var innerDict = {};
  innerDict[Symbol.iterator] = (function () {
      return {
              next: (function (input) {
                  var value = next(state, input);
                  return {
                          value: value,
                          done: Belt_Option.isNone(value)
                        };
                })
            };
    });
  return innerDict;
}

function getSequence(iter) {
  return Js_dict.get(iter, Symbol.iterator)();
}

function make(state, next) {
  return makeWithNextInput(state, (function (state, param) {
                return next(state);
              }));
}

var forOf = ((iterator, fn) => {
  for (let body of iterator) {
      fn(body);
  }
});

export {
  makeWithNextInput ,
  getSequence ,
  make ,
  forOf ,
}
/* No side effect */
