// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";
import * as InjectedForLoopJs from "./InjectedForLoop.js";

function make(state, getNext) {
  var innerDict = {};
  innerDict[Symbol.iterator] = (function () {
      return {
              next: (function () {
                  var value = getNext(state);
                  return {
                          value: value,
                          done: Belt_Option.isNone(value)
                        };
                })
            };
    });
  return innerDict;
}

var Break = /* @__PURE__ */Caml_exceptions.create("Iterator.Break");

var Continue = /* @__PURE__ */Caml_exceptions.create("Iterator.Continue");

function $$break() {
  throw {
        RE_EXN_ID: Break,
        Error: new Error()
      };
}

function $$continue() {
  throw {
        RE_EXN_ID: Continue,
        Error: new Error()
      };
}

function forOf(prim0, prim1) {
  InjectedForLoopJs.forOf(prim0, prim1);
}

export {
  make ,
  $$break ,
  $$continue ,
  forOf ,
  Break ,
  Continue ,
}
/* ./InjectedForLoop.js Not a pure module */
