// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";
import * as InjectedForOfJs from "./InjectedForOf.js";

function make(state, getNext, isDone) {
  var innerDict = {};
  innerDict[Symbol.iterator] = (function () {
      return {
              next: (function () {
                  var done = isDone(state);
                  return {
                          value: getNext(state),
                          done: done
                        };
                })
            };
    });
  return innerDict;
}

var Break = /* @__PURE__ */Caml_exceptions.create("Iterator.Break");

var Continue = /* @__PURE__ */Caml_exceptions.create("Iterator.Continue");

function $$break() {
  throw {
        RE_EXN_ID: Break,
        Error: new Error()
      };
}

function $$continue() {
  throw {
        RE_EXN_ID: Continue,
        Error: new Error()
      };
}

function forOf(prim0, prim1) {
  InjectedForOfJs.forOf(prim0, prim1);
}

export {
  make ,
  $$break ,
  $$continue ,
  forOf ,
}
/* ./InjectedForOf.js Not a pure module */
